apiVersion: v1
appVersion: V1.0
description: 'Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.'
name: wrc
version: 0.1.0
home: wrc.zaakonline.nl
icon: wrc.zaakonline.nl